// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbibgoztpxzusqawwhaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiaWJnb3p0cHh6dXNxYXd3aGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDY2NTYsImV4cCI6MjA2NTg4MjY1Nn0.aMeWFVI0blBisl5RWSdLwU8D3NHhOA0Dm-r3XIxqm8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);